from django.urls import path

from interview import views

urlpatterns=[
    path('',views.main,name='main'),
    path('adminhm',views.adminhm,name='adminhm'),
    path('block_or_unblock',views.block_or_unblock,name='block_or_unblock'),
    path('manage_guide',views.manage_guide,name='manage_guide'),
    path('send_reply',views. send_reply,name='send_reply'),
    path('Verify_company',views.Verify_company,name='Verify_company'),
    path('view_complaint',views.view_complaint,name='view_complaint'),
    path('view_review',views.view_review,name='view_review'),
    path('viewuser',views.viewuser,name='viewuser'),
    path('add_job_veccancy',views.add_job_veccancy,name='add_job_veccancy'),
    path('chat_with_candidate',views.chat_with_candidate,name='chat_with_candidate'),
    path('company_home',views.company_home,name='company_home'),
    path('Mange_job_veccancy',views.Mange_job_veccancy,name='Mange_job_veccancy'),
    path('verify_application',views.verify_application,name='verify_application'),
    path('Add_question',views.Add_question,name='Add_question'),
    path('add_text_type',views.add_text_type,name='add_text_type'),
    path('add_tips',views.add_tips,name='add_tips'),
    path('Guid_home', views.Guid_home, name='Guid_home'),
    path('manage_question', views.manage_question, name='manage_question'),
    path('manage_test_type',views.manage_test_type,name='manage_test_type'),
    path(' Send_reply', views. Send_reply, name=' Send_reply'),
    path('view_doubt',views.view_doubt,name='view_doubt'),
    path('view_guid_line', views.view_guid_line, name='view_guid_line'),
    path('view_Review',views.view_Review,name='view_Review'),
    path('log_out', views.log_out, name='log_out'),
    path('log_in', views.log_in, name='log_in'),
    path('add_guide', views.add_guide, name='add_guide'),
    path('edit_guide/<int:id>', views.edit_guide, name='edit_guide'),
    path('add_guidecode', views.add_guidecode, name='add_guidecode'),
    path('viewusersearch', views.viewusersearch, name='viewusersearch'),
    path('manageguidesearch', views.manageguidesearch, name='manageguidesearch'),
    path('company_search', views.company_search, name='company_search'),
    path('viewreviewsearch', views.viewreviewsearch, name='viewreviewsearch'),
    path('edit_guide_post', views.edit_guide_post, name='edit_guide_post'),
    path('delete_guide/<int:id>', views.delete_guide, name='delete_guide'),
    path('block_guide/<int:id>', views.block_guide, name='block_guide'),
    path('unblock_guide/<int:id>', views.unblock_guide, name='unblock_guide'),
    path('reply/<int:id>', views.reply, name='reply'),
    path('sendreply', views.sendreply, name='sendreply'),
    path('accept/<int:id>', views.accept, name='accept'),
    path('reject/<int:id>', views.reject, name='reject'),
    path('company_register', views.company_register, name='company_register'),
    path('add_register', views.add_register, name='add_register'),


    path('company_home', views.company_home, name='company_home'),
    path('Manage_job_veccancy', views.Manage_job_veccancy, name='Manage_job_veccancy'),
    path('add_veccancy', views.add_veccancy, name='add_veccancy'),

    # path('add_vacancy',views.add_vacancy, name='add_vacancy'),
  #home
    path('applicationsearch', views.applicationsearch, name='applicationsearch'),
    path('acceptapplication/<int:id>', views.acceptapplication, name='acceptapplication'),
    path('rejectapplication/<int:id>', views.rejectapplication, name='rejectapplication'),
]