from django.urls import path

from interview import views

urlpatterns=[
    path('',views.main,name='main'),
    path('logout',views.logout,name='logout'),
    path('adminhm',views.adminhm,name='adminhm'),
    path('block_or_unblock',views.block_or_unblock,name='block_or_unblock'),
    path('manage_guide',views.manage_guide,name='manage_guide'),
    path('send_reply',views. send_reply,name='send_reply'),
    path('Verify_company',views.Verify_company,name='Verify_company'),
    path('view_complaint',views.view_complaint,name='view_complaint'),
    path('view_review',views.view_review,name='view_review'),
    path('viewuser',views.viewuser,name='viewuser'),
    path('add_job_veccancy',views.add_job_veccancy,name='add_job_veccancy'),
    path('chat_with_candidate',views.chat_with_candidate,name='chat_with_candidate'),
    path('company_home',views.company_home,name='company_home'),
    path('Mange_job_veccancy',views.Mange_job_veccancy,name='Mange_job_veccancy'),
    path('verify_application',views.verify_application,name='verify_application'),
    path('add_question',views.add_question,name='add_question'),
    path('add_question_post', views.add_question_post, name='add_question_post'),
    path('Testsearch', views.Testsearch, name='Testsearch'),
    path('delete_Question/<int:id>', views.delete_Question, name='delete_Question'),
    path('add_text_type',views.add_text_type,name='add_text_type'),
    path(' Send_reply', views. Send_reply, name=' Send_reply'),
    path('view_doubt',views.view_doubt,name='view_doubt'),
    path('view_doubt_search',views.view_doubt_search,name='view_doubt_search'),
    path('view_guid_line', views.view_guid_line, name='view_guid_line'),
    path('add_guidlines', views.add_guidlines, name='add_guidlines'),
    path('addguidlines', views.addguidlines, name='addguidlines'),
    # path('log_out', views.log_out, name='log_out'),
    path('log_in', views.log_in, name='log_in'),
    path('add_guide', views.add_guide, name='add_guide'),
    path('edit_guide/<int:id>', views.edit_guide, name='edit_guide'),
    path('add_guidecode', views.add_guidecode, name='add_guidecode'),
    path('edit_Question/<int:id>', views.edit_Question, name='edit_Question'),
    path('edit_question_post', views.edit_question_post, name='edit_question_post'),
    path('viewusersearch', views.viewusersearch, name='viewusersearch'),
    path('manageguidesearch', views.manageguidesearch, name='manageguidesearch'),
    path('company_search', views.company_search, name='company_search'),
    path('viewreviewsearch', views.viewreviewsearch, name='viewreviewsearch'),
    path('edit_guide_post', views.edit_guide_post, name='edit_guide_post'),
    path('delete_guide/<int:id>', views.delete_guide, name='delete_guide'),
    path('block_guide/<int:id>', views.block_guide, name='block_guide'),
    path('unblock_guide/<int:id>', views.unblock_guide, name='unblock_guide'),
    path('reply/<int:id>', views.reply, name='reply'),
    path('sendreply', views.sendreply, name='sendreply'),
    path('accept/<int:id>', views.accept, name='accept'),
    path('reject/<int:id>', views.reject, name='reject'),
    path('company_register', views.company_register, name='company_register'),
    path('add_register', views.add_register, name='add_register'),
    path('company_home', views.company_home, name='company_home'),
    path('Manage_job_veccancy', views.Manage_job_veccancy, name='Manage_job_veccancy'),
    path('add_veccancy', views.add_veccancy, name='add_veccancy'),
    path('edit_job/<int:id>', views.edit_job, name='edit_job'),
    path('edit_veccancy', views.edit_veccancy, name='edit_veccancy'),
    path('delete_vaccancy/<int:id>', views.delete_vaccancy, name='delete_vaccancy'),
    path('Guid_home', views.Guid_home, name='Guid_home'),
    path('manage_question', views.manage_question, name='manage_question'),
    path('manage_test_type', views.manage_test_type, name='manage_test_type'),
    path('add_test', views.add_test, name='add_test'),
    path('addtest', views.addtest, name='addtest'),
    path('edit_test/<int:id>', views.edit_test, name='edit_test'),
    path('edit_test_post', views.edit_test_post, name='edit_test_post'),
    path('delete_test/<int:id>', views.delete_test, name='delete_test'),
    path('add_tips', views.add_tips, name='add_tips'),
    path('addtips', views.addtips, name='addtips'),
    path('view_tips', views.view_tips, name='view_tips'),
    path('doubtreply/<int:id>', views.doubtreply, name='doubtreply'),
    path('doubt_reply', views.doubt_reply, name='doubt_reply'),

    # path('add_vacancy',views.add_vacancy, name='add_vacancy'),
  #home
    path('applicationsearch', views.applicationsearch, name='applicationsearch'),
    path('acceptapplication/<int:id>', views.acceptapplication, name='acceptapplication'),
    path('rejectapplication/<int:id>', views.rejectapplication, name='rejectapplication'),

    path('view_Review',views.view_Review,name='view_Review'),
    path('viewReviewsearch', views.viewReviewsearch, name='viewReviewsearch'),

    path('chatview', views.chatview, name='chatview'),
    path('add_vac_qstion/<id>', views.add_vac_qstion, name='add_vac_qstion'),
    path('coun_msg/<int:id>', views.coun_msg, name='coun_msg'),
    path('coun_insert_chat/<str:msg>/<int:id>', views.coun_insert_chat, name='coun_insert_chat'),

path('Userregistration', views.Userregistration, name='Userregistration'),
path('test_result1', views.test_result1, name='test_result1'),
    path('login2', views.login2, name='login2'),
    path('view_comp_reply', views.view_comp_reply, name='view_comp_reply '),
    path('sendcomp', views.sendcomp, name='sendcomp'),
    path('view_dbt_reply',views.view_dbt_reply,name='view_dbt_reply'),
    path('senddbt', views.senddbt, name='senddbt'),
    path('view_gd', views.view_gd, name='view_gd'),
    path('view_tips', views.view_tips, name='view_tips'),
    path('view_cp', views.view_cp, name='view_cp'),
    path('view_company', views.view_company, name='view_company'),
    path('view_rules', views.view_rules, name='view_rules'),
    path('in_message2', views.in_message2, name='in_message2'),
    path('view_message2', views.view_message2, name='view_message2'),
    path('view_exam', views.view_exam, name='view_exam'),
    path('get_question', views.get_question, name='get_question'),
    path('answertest', views.answertest, name='answertest'),
    path('upldcv', views.upldcv, name='upldcv'),
    path('career_prediction', views.career_prediction, name='career_prediction'),
    path('mocktest', views.mocktest, name='mocktest'),
    path('and_view_questions', views.and_view_questions, name='and_view_questions'),
    path('voice', views.voice, name='voice'),
    path('mark', views.mark, name='mark'),
    path('result', views.result, name='result'),
    path('view_test', views.view_test, name='view_test'),
    path('view_tips1', views.view_tips1, name='view_tips1'),
    path('test_result1', views.test_result1, name='test_result1'),

]