# Generated by Django 3.2.21 on 2024-01-10 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideline',
            name='COMPANY',
        ),
        migrations.AddField(
            model_name='guideline',
            name='GUIDE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interview.guide'),
            preserve_default=False,
        ),
    ]
