# Generated by Django 3.2.22 on 2024-02-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vac_qn',
            name='Question',
            field=models.CharField(max_length=600),
        ),
    ]
