# Generated by Django 3.2.21 on 2023-12-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complaint',
            new_name='Complaint_table',
        ),
    ]
