# Generated by Django 3.2.21 on 2023-12-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_rename_complaint_complaint_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccancy',
            old_name='vaccancy',
            new_name='Vaccancy',
        ),
    ]
